# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        types:
          - python
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args:
          - --fix
        stages:
          - commit
      - id: ruff-format
        stages:
          - commit

      - id: ruff
        name: ruff-check
        stages:
          - manual

      - id: ruff-format
        name: ruff-format-check
        args:
          - --diff
        stages:
          - manual

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args:
          - --strict
          - --no-warn-no-return
          - --python-version=3.8
        exclude: "^tests/"
        language: system
        types: [ python ]
        require_serial: true
