# https://taskfile.dev

version: '3'

tasks:
  fix: pre-commit run --all-files --hook-stage commit
  mypy: pre-commit run --all-files mypy
  coverage:
    cmds:
      - pytest --cov
      - coverage html
      - python -m webbrowser -t htmlcov/index.html
