# https://taskfile.dev

version: '3'

tasks:
  fix: pre-commit run --all-files --hook-stage commit
  mypy: pre-commit run --all-files mypy
  tox: docker run --name sentry-offline-tox --rm -it -v `pwd`:/tests -u 1000 31z4/tox:4.15.0-4.0.8 -q {{.CLI_ARGS}}
  coverage:
    cmds:
      - pytest --cov
      - coverage html
      - python -m webbrowser -t htmlcov/index.html
