# https://taskfile.dev

version: '3'

tasks:
  fix: pre-commit run --all-files
  coverage:
    cmds:
      - pytest --cov=src/
      - coverage html
      - python -m webbrowser -t htmlcov/index.html
